
export default function () {
  return [
    {
      id: '1',
      text: "Executive Meeting",
      company: 'IBM',
      date: '5',
      subject: 'Data Analyst',
      body: 'Filter Out Best Data Observer',
      attendees: ['Ravi', 'shayam', 'Nandani'],
      start: '10 AM',
      end: '12 PM',
    },
    {
      id: '2',
      text: "Planning on new prospect",
      company: 'WIPRO',
      date: '9',
      subject: 'Web Design',
      body: 'A e-commerce platform',
      attendees: ['Mohan', 'Raghav'],
      start: '11 AM',
      end: '1 PM',
    },
    {
      id: '3',
      text: "Executive Meeting with",
      company: 'IBM',
      date: '15',
      subject: 'Operations',
      body: 'Must be support tech and sales',
      attendees: ['Dinesh', 'Kajal', 'Balaji'],
      start: '12 PM',
      end: '2 PM',
    },
    {
      id: '4',
      text: "Planning on new prospect",
      company: 'WIPRO',
      date: '29',
      subject: 'Health Care',
      body: 'Child and senior citizen',
      attendees: ['Monica', 'Jhon'],
      start: '2 AM',
      end: '3 PM',
    },
    {
      id: '5',
      text: "Executive Meeting",
      company: 'IBM',
      date: '25',
      subject: 'Architecture',
      body: 'Transport C2C courier',
      attendees: ['Pankaj', 'Ragini'],
      start: '11 AM',
      end: '4 PM',
    },
    {
      id: '6',
      text: "Planning on new prospect",
      company: 'INFOSYS',
      date: '19',
      subject: 'Web Application',
      body: 'Details yet to come',
      attendees: ['Hardik', 'Raja'],
      start: '10 AM',
      end: '11 AM',
    }
  ]
}